https://drive.google.com/drive/folders/1xiHsMfcNtG0sDV0B08Hs7mk5MXd3h858?usp=sharing
спустя какое-то количество запусков начал выдавать BadStatusLine, но до этого все было хорошо
у меня нет постоянного доступа к интернету сейчас, поэтому, на случай если ipynb не грузится(сейчас почему-то git тупит) есть py.
